product:
  handler: src/lambdas/product.handler
  timeout: ${self:provider.timeout}
  events:
    - sqs:
        batchSize: ${env:BATCH_SIZE}
        arn:
          Fn::GetAtt:
            - ProductQueue
            - Arn

send-message:
  handler: src/lambdas/send-message.handler
  timeout: ${self:provider.timeout}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - sqs:SendMessage
      Resource: '*'
