ProductQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: '${self:service}-${env:STAGE}'
    VisibilityTimeout: ${self:provider.timeout}
    RedrivePolicy:
      deadLetterTargetArn:
        Fn::GetAtt:
          - ProductDLQ
          - Arn
      maxReceiveCount: 3

ProductDLQ:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: '${self:service}-DLQ-${env:STAGE}'
